learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learnings_logs.urls')),
]

learnings_logs/urls.py
"""Defines URL pattern for learnings_logs."""

from django.urls import path 
from . import views

app_name = 'learnings_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Show all topics.
    path('topics/', views.topics, name='topics'),

    # Details page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topc
    path('new_topic/', views.new_topic, name='new_topic'),

    #Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""defines URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView 

from . import views

app_name = 'users'
urlpatterns =[
    # Login page
    path('login/', 
        LoginView.as_view(
            template_name='users/login.html'
        ), 
        name="login"
    ),
    # Logout page
    path('logout/', views.logout_view, name='logout'),

    # Account creation page
    path('register/', views.register, name='register'),
]

learnings_logs/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        """Return a string representation of the model"""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) >= 50:
            return self.text[:50] + "..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learnings_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic 
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm): 
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learnings_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    """The home page for Learning Log"""
    return render(request, 'learnings_logs/index.html')

def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learnings_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    check_topic_owner(request, topic)
    # if topic.owner != request.user:
    #     raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learnings_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data/
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learnings_logs:topics'))

    context = {'form': form}
    return render(request, 'learnings_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data dubmitted; create a blank form.
        form = EntryForm()
    else:
        # POST data sumbitted; process data.
        form = EntryForm(data=request.POST)
    
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            check_topic_owner(request, topic)
            new_entry.save()
            return HttpResponseRedirect(reverse('learnings_logs:topic', args=[topic_id]))
    context ={'topic': topic, 'form': form}
    return render(request, 'learnings_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    # if topic.owner != request.user:
    #     raise Http404

    if request.method != 'POST':
        #Initial request; pre-fil form with current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learnings_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learnings_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib.auth import login, authenticate 
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learnings_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticate_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticate_user)    
            return HttpResponseRedirect(reverse('learnings_logs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

learnings_logs/templates/learnings_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html land="en">

<head>
    <meta charset="utf-8">
    <meta httpe-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                </button>
                <a class="navbar-brand" href="{% url 'learnings_logs:index' %}">
                    Learning Log
                </a>
            </div>

            <div id="navbar" class="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learnings_logs:topics' %}">Topics</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username | capfirst }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container">

        <div class="page-header">
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>

    </div> <!-- /container -->
</body>

</html>

learnings_logs/templates/learnings_logs/edit_entry.html
{% extends "learnings_logs/base.html" %}

{% block content %}
    <p><a href="{% url 'learnings_logs:topic' topic.id %}">{{topic}}</a></p>
    
    <p>Edit entry:</p>

    <form action="{% url 'learnings_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <button name=""submit">save changes</button>
    </form>

{% endblock content %}

learnings_logs/templates/learnings_logs/index.html
{% extends "learnings_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log, and list the topics you're elarning about.
    </h2>
    <h2>
        Whenever you learn something new about a toic, make an entry summarizing what you've learned.
    </h2>
{% endblock content %}

learnings_logs/templates/learnings_logs/new_entry.html
{% extends "learnings_logs/base.html" %}

{% block content %} 
    
    <p><a href="{% url 'learnings_logs:topic' topic.id %}">{{ topic }}</a></p>
    
    <p>Add a new entry:</p>
    <form action="{% url 'learnings_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button>
    </form>

{% endblock content %}

learnings_logs/templates/learnings_logs/new_topic.html
{% extends "learnings_logs/base.html" %}

{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learnings_logs:new_topic' %}" method='post' class="col-lg-4">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" clas="btn btn-primary">add topic</button>          
        {% endbuttons %}
    </form>

{% endblock content %}

learnings_logs/templates/learnings_logs/topic.html
{% extends 'learnings_logs/base.html' %}

{% block content %}
    
    <p>Topic: {{ topic }}</p>

    <p> Entries:</p>
    <p>
    <a href="{% url 'learnings_logs:new_entry' topic.id %}">add new entry</a>
    </p>
    <ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learnings_logs:edit_entry' entry.id %}">edit entry</a>
        </p>
    </li>
    {% empty %}
    <li>
        There are no entries for this topic yet.
    </li>
    {% endfor %}
    </ul>

{% endblock content %}

learnings_logs/templates/learnings_logs/topics.html
{% extends "learnings_logs/base.html" %}

{% block content %}

    <p>Topics
        <ul>
            {% for topic in topics %}
                <li>
                <a href="{% url 'learnings_logs:topic' topic.id %}">{{ topic }}</a>
                </li>
            {% empty %}
                <li style="color:red">No topics have been added yet.</li>
            {% endfor %}
        </ul>
        <a href="{% url 'learnings_logs:new_topic' %}">Add a new topic:</a>

    </p>


{% endblock content %}

<!-- style="color:blue">{{topic }} -->

users/templates/users/login.html
{% extends "learnings_logs/base.html" %}

{% load bootstrap3 %}
{% block header %}
<h2>
    Log in to your account.
</h2>
{% endblock header %}

{% block content %}

<form method="post" action="{% url 'users:login' %}" class="col-lg-4">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Login</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'learnings_logs:index' %}"/>
</form>
{% endblock content %}

users/templates/users/register.html
{% extends "learnings_logs/base.html" %}

{% block content %}
    <form method="post" action ="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'learnings_logs:index' %}"/>
    </form>
{% endblock content %}